### PR TITLE
Update Changelog

### PR DESCRIPTION
**Pull request by gwenwindflower**

### CODE REVIEW

**Comment by pnadolny13** [comment]
@gwenwindflower is it possible to get this merged with a release? To have https://github.com/dbt-labs/dbt-codegen/pull/168 supported without pinning to a git branch 😄 . I'm happy to help with anything needed to get it across the finish line!

**Comment by gwenwindflower** [comment]
@pnadolny13 huge apologies! i had some serious health issues crop up and was out of office for a bit, and it's taking me some time to get fully recalibrated. i'm going to block out time Monday and Tuesday to catch up all the `codegen` things. Appreciate you!

**Comment by pnadolny13** [comment]
>huge apologies! i had some health issues crop up and was out of office for a bit, and it's taking me some time to get fully recalibrated

No worries! Sorry to hear that, I hope everything is ok. Let me know if theres anything I can help with 😄

**Review by dave-connors-3 — APPROVED** [review]

**Comment by dataders** [comment]
linking https://github.com/dbt-labs/dbt-adapters/issues/178 as what screwed up the integration tests

**Pull request merged**
