### PR TITLE
Expected result of nested struct in BigQuery

### LINKED ISSUE #98: Alias nested sub-structs for bigquery
The following was originally reported and described [here](https://github.com/dbt-labs/dbt-codegen/pull/54/files#r1053066744) by @Zatte

### Describe the bug

Output will be ambiguous in the case of multiple sub-structs (nested columns) with the same name.

### Steps to reproduce
Use the dbt-bigquery adapter and the following files:

`packages.yml`
```
packages:
  - package: dbt-labs/codegen
    version: 0.9.0
```

`models/model_struct.sql`
```sql
select 
   struct(
      "a1" as a, 
      "b1" as b
   ) as substruct1, 
   struct(
      "a2" as a, 
      "b2" as b
   ) as substruct2
```

Then run the following:
```shell
dbt deps
dbt run-operation generate_model_yaml --args '{"model_names": ["model_struct"]}'
```

### Expected results
```yaml
version: 2

models:
  - name: model_struct
    description: ""
    columns:
      - name: substruct1
        description: ""

      - name: substruct1.a
        description: ""

      - name: substruct1.b
        description: ""

      - name: substruct2
        description: ""

      - name: substruct2.a
        description: ""

      - name: substruct2.b
        description: ""
```

### Actual results
```yaml
version: 2

models:
  - name: model_struct
    description: ""
    columns:
      - name: substruct1
        description: ""

      - name: a
        description: ""

      - name: b
        description: ""

      - name: substruct2
        description: ""

      - name: a
        description: ""

      - name: b
        description: ""
```

### System information

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
 $ dbt --version
Core:
  - installed: 1.3.1
  - latest:    1.3.1 - Up to date!

Plugins:
  - bigquery: 1.3.0 - Up to date!
  ```

### Are you interested in contributing the fix?
I'll open a PR for this. The most time-consuming part will be modifying the integration tests.

Simple fix is described [here](https://github.com/dbt-labs/dbt-codegen/pull/54/files#r1052133901):

```diff
-     {% do model_yaml.append('      - name: ' ~ column.name | lower ) %}
+     {% do model_yaml.append('      - name: ' ~ column_name  | lower ) %}
```

This fix is verified to work as described in my local environment.

### PR DESCRIPTION
**Pull request by dbeatty10**
resolves #98

This is a:
- [ ] documentation update
- [x] bug fix with no breaking changes
- [ ] new functionality
- [ ] a breaking change

All pull requests from community contributors should target the `main` branch (default).

## Checklist
- [x] This code is associated with an issue which has been triaged and [accepted for development](https://docs.getdbt.com/docs/contributing/oss-expectations#pull-requests). 
- [x] I have verified that these changes work locally
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [x] I have added an entry to CHANGELOG.md

### CODE REVIEW

**Comment by Zatte** [comment]
Adding this as a note as it is more of feature/discussion than a bugfix. 

I've seen that you can document nested columns in multiples ways.

One way being 
```yaml
models:
  - name: model_struct
    description: ""
    columns:
      - name: analytics
      - name: analytics.source
      - name: analytics.medium
      - name: analytics.source_medium
```

But there is also the possibility to do (note the nested use of the key `columns` inside a column)
```yaml
models:
  - name: model_struct
    columns:
      - name: analytics
        columns:
          - name: source
          - name: medium
          - name: source_medium
```

Since this macro makes favors of one over the other it would be nice to make a small note about this decision. I believe both to be identical but I haven't looked into it sufficiently to be sure. 

A feature request could be to support both or deprecate one method upstream(dbt-core) to encourage consistency. At the very least document (in the official docs) the canonical way for documenting nested fields (might be done but my google-fu wasn't strong enough).

**Comment by dbeatty10** [comment]
> I've seen that you can document nested columns in multiples ways.

Good point!

In my experiments, the two variants behaved differently when adding descriptions and then generating the documentation:
```shell
dbt docs generate
dbt docs serve
```

In my quick tests, your first example rendered the descriptions, but the second didn't.

Are you able to get it to include the descriptions when generating and serving the docs?

Here's the exact code I used:

`models/model_struct.sql`
```sql
select 
   struct(
      "a1" as source, 
      "b1" as medium, 
      "c1" as source_medium
   ) as analytics
```

Worked:
`models/_models.yml`
```yaml
version: 2

models:
  - name: model_struct
    columns:
      - name: analytics
        description: "This is the name of the STRUCT"
      - name: analytics.source
        description: "This is the first attribute in the STRUCT"
      - name: analytics.medium
        description: "This is the second attribute in the STRUCT"
      - name: analytics.source_medium
        description: "This is the third attribute in the STRUCT"
```

image


Didn't work:
`models/_models.yml`
```yaml
version: 2

models:
  - name: model_struct
    columns:
      - name: analytics
        description: "This is the name of the STRUCT"
        columns:
          - name: source
            description: "This is the first attribute in the STRUCT"
          - name: medium
            description: "This is the second attribute in the STRUCT"
          - name: source_medium
            description: "This is the third attribute in the STRUCT"
```

image

**Comment by Zatte** [comment]
> Are you able to get it to include the descriptions when generating and serving the docs?

No, you are correct, the current macro approach works better and they are not the same! Thanks for clarifying and the great velocity on this Issue/PR 💯

**Comment by dbeatty10** [comment]
Thanks for reporting this and all your detailed information @Zatte ! Wouldn't have happened without you 🏅

**Pull request merged**
